#!/bin/sh
#
# Start the gpio...
#

case "$1" in
  start)
	printf "Starting gpio: "
	echo 17 > /sys/class/gpio/export && \
	echo out > /sys/class/gpio/gpio17/direction && \
	chmod go+w /sys/class/gpio/gpio17/value
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping gpio: "
	echo 17 > /sys/class/gpio/unexport 
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

