#!/bin/sh
#
# Start the moduli2c...
#

case "$1" in
  start)
    modprobe i2c-bcm2835 && \
    #modprobe i2c-dev && \
    modprobe bmp280-i2c && \
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping moduli2c: "
    modprobe -r i2c-bcm2835 && \
    #modprobe -r i2c-dev && \
    modprobe -r bmp280-i2c && \
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit $?        
