#!/bin/sh

# Help 

Help()
{
   # Display Help
   echo "Make the project and update the m5sum of the desired filesystem."
   echo "When the m5sum of rootfs.ext4 or boot.vfat, connected weather stations will try to update their version. "
   echo
   echo "Syntax: updateversion [-r|b]"
   echo "options: (default -r)"
   echo "r   update the md5sum of rootfs.ext4 ."
   echo "b   update the md5sum of boot.vfat ."
   echo
}

# md5sumrootfs

md5sumrootfs ()
{
   echo "Copying of rootfs.ext4 in UPDATE and calculating its md5sum"
   cp /home/dev/buildroot/buildroot-2022.02.2/output/images/rootfs.ext4 /home/dev/buildroot/UPDATE/
   md5sum /home/dev/buildroot/buildroot-2022.02.2/output/images/rootfs.ext4 | awk '{ print $1 }'  > /home/dev/buildroot/UPDATE/md5sum.rootfs
}

# md5sumboot

md5sumboot ()
{
   echo "Copying of boot.vfat in UPDATE and calculating its md5sum"
   cp /home/dev/buildroot/buildroot-2022.02.2/output/images/boot.vfat /home/dev/buildroot/UPDATE/
   md5sum /home/dev/buildroot/buildroot-2022.02.2/output/images/boot.vfat | awk '{ print $1 }'  > /home/dev/buildroot/UPDATE/md5sum.boot
}


############################################################
# Main program                                             #
############################################################

# Get the options
if [ -z "$1" ]
then
   varmd5sumrootfs="true" 
else
   while getopts "hrb" option; do  
      case $option in  
       h) # display Help
            Help
            exit;;
       r) # update the md5sum of rootfs.ext4
            varmd5sumrootfs="true"  
            ;;
       b) # update the md5sum of boot.vfat
            varmd5sumboot="true"  
            ;;
         \?) # Invalid arg
           echo "Error: Invalid arg"
            exit 1;;
      esac
   done 
fi

(cd /home/dev/buildroot/buildroot-2022.02.2/; make)

if [ ! -z "$varmd5sumrootfs" ]
then
   md5sumrootfs
fi

if [ ! -z "$varmd5sumboot" ]
then
   md5sumboot
fi


